apiVersion: v1
kind: Secret
metadata:
  name: placement-secrets
  namespace: placement
  labels:
    app.kubernetes.io/name: college-placement-app
    app.kubernetes.io/part-of: college-placement-app
type: Opaque
data:
  # The base64 values below correspond to default dummy credentials.
  # Generate new values using: echo -n "your_secret_value" | base64
  
  # Default: db_admin
  mongo-root-username: ZGJfYWRtaW4=
  
  # Default: admin
  mongo-root-password: YWRtaW4=
  
  # Default: jd6Hrad5rLriygtzDsyvUoMXTU4Rmyv1vLbrN1MLVvj
  jwt-access-secret: amQ2SHJhZDVyTHJpeWd0ekRzeXZVb01YVFU0Um15djF2TGJyTjFNTFZ2ag==
  
  # Default: jd6Hrad5rLriygtzDsyvUoMXTU4Rmyv1vLbrN1MLVvj
  jwt-refresh-secret: amQ2SHJhZDVyTHJpeWd0ekRzeXZVb01YVFU0Um15djF2TGJyTjFNTFZ2ag==
