apiVersion: v1
kind: Secret
metadata:
  name: {{ include "placement-portal.fullname" . }}-secrets
  labels:
    {{- include "placement-portal.commonLabels" . | nindent 4 }}
type: Opaque
data:
  mongo-root-username: {{ .Values.secrets.mongoRootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.secrets.mongoRootPassword | b64enc | quote }}
  jwt-access-secret: {{ .Values.secrets.jwtAccessSecret | b64enc | quote }}
  jwt-refresh-secret: {{ .Values.secrets.jwtRefreshSecret | b64enc | quote }}
